services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password123}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-powerplants}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  power-plants:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - MONGO_HOST=mongodb
    volumes:
      - ./src/data:/app/dist/data
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongodb_data: